version: "3.7"

services:
  # NGINX PROXY
  nginx-proxy:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx-proxy
    volumes:
      - ./nginx/web-app-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx_headers.conf:/etc/nginx/nginx_headers.conf
    ports:
      - "80:80"
      
  # VAULT AGENT
  vault-agent:
    image: hashicorp/vault
    container_name: vault-agent
    privileged: true
    environment:
      VAULT_ADDR: "https://hcvault-sandbox.llm-aws.com:8200/"
    volumes:
      - ./vault-config:/etc/vault.d
      - ./web/configs/:/home/vault/
    command: ["sh", "-c", "vault agent -config=/etc/vault.d/vault-agent.hcl"]

  # WEB APP RENDER
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app-render
    volumes:
      - ./web/configs/:/app/configs
    environment:
      NODE_PATH: /jsproject/node_modules